#name: CI/CD – ClientService
#
#on:
#  push:
#    branches: [ main_2 ]
#  pull_request:
#
#env:
#  AWS_REGION: us-east-1
#  ECR_REPO_NAME: clientservice
#  TF_DIR: infra      # pasta com seus .tf
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: actions/setup-python@v5
#        with:
#          python-version: "3.12"
#
#      - name: Install deps
#        run: |
#          pip install --upgrade pip
#          pip install -r requirements.txt
#          pip install pytest pytest-cov coverage
#
#      - name: Run tests + coverage
#        run: |
#          # gera XML para sonar/cloud e imprime relatório no log
#          pytest --cov=app --cov-report=xml --cov-report=term-missing --cov-fail-under=80
#
#      - name: Upload coverage artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: coverage-xml
#          path: coverage.xml
#
#  validate_terraform:
#    name: Validate Terraform
#    runs-on: ubuntu-latest
#    needs: test
#    defaults:
#      run:
#        working-directory: ${{ env.TF_DIR }}
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v2
#        with:
#          terraform_version: 1.7.5
#
#      - name: Terraform Init
#        run: terraform init -input=false
#
#      - name: Terraform Validate
#        run: terraform validate
#
#      - name: Terraform Plan
#        run: terraform plan -out=plan.binary
#
#  deploy:
#    name: Deploy to AWS
#    runs-on: ubuntu-latest
#    needs: [test, validate_terraform]
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
#          aws-region:            ${{ env.AWS_REGION }}
#
#      # ... restante inalterado (Terraform apply, Docker build/push, ECS update, migrações) ...
