name: CI/CD – Build, Push, Terraform

on:
  push:
    branches: [main, master]

env:
  AWS_REGION:   us-east-1                # ajuste se necessário
  SERVICE_NAME: client-service
  PORT:         8000

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Credenciais (vêm do AWS Academy, role voclabs já tem ECR PutImage)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}
          role-skip-session-tagging: true

      # Login & tag dinâmica
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr

      # Build & push
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # Terraform
      - uses: hashicorp/setup-terraform@v2
        with: { terraform_version: 1.7.5 }

      - name: Terraform Init & Apply
        working-directory: infra
        env:
          TF_VAR_aws_region     : ${{ env.AWS_REGION }}
          TF_VAR_service_name   : ${{ env.SERVICE_NAME }}
          TF_VAR_container_port : ${{ env.PORT }}
          TF_VAR_image_uri      : ${{ steps.ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          TF_VAR_exec_role_name : LabRole                       # ou outro nome se diferente
          TF_VAR_db_host        : ${{ secrets.DB_HOST }}
          TF_VAR_db_port        : ${{ secrets.DB_PORT }}
          TF_VAR_db_user        : ${{ secrets.DB_USER }}
          TF_VAR_db_password    : ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_name        : ${{ secrets.DB_NAME }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false

      # Exibe URL do ALB
      - name: Show app URL
        working-directory: infra
        run: echo "::notice title=URL::$(terraform output -raw alb_dns)"
