name: Deploy AWS – Client-Service
on:
  push:
    branches: [master]

env:
  AWS_REGION: us-east-1
  SERVICE_NAME: client-service
  PORT: 8000

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
# 1 Código
    - uses: actions/checkout@v4

# 2 Credenciais do lab
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region:            ${{ env.AWS_REGION }}
        role-skip-session-tagging: true

# 3 Account ID
    - id: acct
      run: echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

# 4 Terraform CLI
    - uses: hashicorp/setup-terraform@v2
      with: { terraform_version: 1.7.5 }

# ───────────────────
# Fase ECR
# ───────────────────
    - name: Terraform – ECR
      working-directory: infra/ecr
      env:
        TF_VAR_aws_region    : ${{ env.AWS_REGION }}
        TF_VAR_ecr_repo_name : ${{ env.SERVICE_NAME }}
      run: |
        terraform init -input=false
        terraform apply -auto-approve -input=false || \
        terraform import aws_ecr_repository.app_repo ${SERVICE_NAME}

# 5 Define REPO_URL para as próximas etapas
    - id: repo
      run: echo "REPO_URL=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${SERVICE_NAME}" >> $GITHUB_ENV

# 6 Login ECR (precisa Allow ecr:GetAuthorizationToken)
    - run: |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin $REPO_URL

# 7 Build & push
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.REPO_URL }}:${{ github.sha }}

      # ───────────────────────────────
      # Importa ALB, Target-Group e SG
      # ───────────────────────────────
    - name: Importar recursos ALB/TG/SG se já existirem
      working-directory: infra/ecs
      run: |
        terraform init -input=false

        # Descobre ARNs/IDs (retorna "" se não existir)
        LB_ARN=$(aws elbv2 describe-load-balancers \
                   --names "${SERVICE_NAME}-alb" \
                   --query 'LoadBalancers[0].LoadBalancerArn' \
                   --output text 2>/dev/null || true)

        TG_ARN=$(aws elbv2 describe-target-groups \
                   --names "${SERVICE_NAME}-tg" \
                   --query 'TargetGroups[0].TargetGroupArn' \
                   --output text 2>/dev/null || true)

        SG_ID=$(aws ec2 describe-security-groups \
                  --filters "Name=group-name,Values=${SERVICE_NAME}-alb-sg" \
                  --query 'SecurityGroups[0].GroupId' \
                  --output text 2>/dev/null || true)

        # Importa somente se o recurso existir
        [ -n "$LB_ARN" ] && [ "$LB_ARN" != "None" ] && \
          terraform import -input=false aws_lb.app "$LB_ARN" || true

        [ -n "$TG_ARN" ] && [ "$TG_ARN" != "None" ] && \
          terraform import -input=false aws_lb_target_group.tg "$TG_ARN" || true

        [ -n "$SG_ID" ] && [ "$SG_ID" != "None" ] && \
          terraform import -input=false aws_security_group.alb_sg "$SG_ID" || true

      # ───────────────────
# Fase ECS / ALB
# ───────────────────
    - name: Terraform – ECS/ALB
      working-directory: infra/ecs
      env:
        TF_VAR_aws_region     : ${{ env.AWS_REGION }}
        TF_VAR_service_name   : ${{ env.SERVICE_NAME }}
        TF_VAR_container_port : ${{ env.PORT }}
        TF_VAR_image_uri      : ${{ env.REPO_URL }}:${{ github.sha }}
        TF_VAR_exec_role_name : LabRole
        TF_VAR_db_host        : ${{ secrets.DB_HOST }}
        TF_VAR_db_port        : ${{ secrets.DB_PORT }}
        TF_VAR_db_user        : ${{ secrets.DB_USER }}
        TF_VAR_db_password    : ${{ secrets.DB_PASSWORD }}
        TF_VAR_db_name        : ${{ secrets.DB_NAME }}
      run: |
        terraform apply -auto-approve -input=false

# 8 Exibe URL
    - name: Show URL
      working-directory: infra/ecs
      run: echo "::notice title=ALB URL::$(terraform output -raw alb_dns)"
