name: PR Validation

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8

      - name: Lint (flake8)
        run: |
          flake8 app

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml --cov-fail-under=70

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  sonar_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install scanner
        run: |
          pip install sonar-scanner

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.login=$SONAR_TOKEN

      # Para SonarCloud, use a action oficial:
      # - uses: sonarsource/sonarcloud-github-action@v2
      #   with:
      #     projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
      #     organization: ${{ secrets.SONAR_ORGANIZATION }}
      #     token: ${{ secrets.SONAR_TOKEN }}
